export const catholicBookIds_de = [
  { id: "das-buch-genesis",                   name: "Genesis",               size: 50 },
  { id: "das-buch-exodus",                    name: "Exodus",                size: 40 },
  { id: "das-buch-levitikus",                 name: "Levitikus",             size: 27 },
  { id: "das-buch-numeri",                    name: "Numeri",                size: 36 },
  { id: "das-buch-deuteronomium",             name: "Deuteronomium",         size: 34 },
  { id: "das-buch-josua",                     name: "Josua",                 size: 24 },
  { id: "das-buch-der-richter",               name: "Richter",               size: 21 },
  { id: "das-buch-rut",                       name: "Rut",                   size: 4  },
  { id: "das-erste-buch-samuel",              name: "1. Samuel",             size: 31 },
  { id: "das-zweite-buch-samuel",             name: "2. Samuel",             size: 24 },
  { id: "das-erste-buch-der-konige",          name: "1. Könige",             size: 22 },
  { id: "das-zweite-buch-der-konige",         name: "2. Könige",             size: 25 },
  { id: "das-erste-buch-der-chronik",         name: "1. Chronik",            size: 29 },
  { id: "das-zweite-buch-der-chronik",        name: "2. Chronik",            size: 36 },
  { id: "das-buch-esra",                      name: "Esra",                  size: 10 },
  { id: "das-buch-nehemia",                   name: "Nehemia",               size: 13 },
  { id: "das-buch-tobit",                     name: "Tobit",                 size: 14 },
  { id: "das-buch-judit",                     name: "Judit",                 size: 16 },
  { id: "das-buch-ester",                     name: "Ester",                 size: 10 },
  { id: "das-erste-buch-der-makkabaer",       name: "1. Makkabäer",          size: 16 },
  { id: "das-zweite-buch-der-makkabaer",      name: "2. Makkabäer",          size: 15 },
  { id: "das-buch-ijob",                      name: "Iob",                   size: 42 },
  { id: "die-psalmen",                        name: "Psalmen",               size: 150 },
  { id: "das-buch-der-sprichworter",          name: "Sprüche",               size: 31 },
  { id: "das-buch-kohelet",                   name: "Kohelet",               size: 12 },
  { id: "das-hohelied",                       name: "Hohelied",              size: 8  },
  { id: "das-buch-der-weisheit",              name: "Weisheit",              size: 19 },
  { id: "das-buch-jesus-sirach",              name: "Sirach",                size: 51 },
  { id: "das-buch-jesaja",                    name: "Jesaja",                size: 66 },
  { id: "das-buch-jeremia",                   name: "Jeremia",               size: 52 },
  { id: "die-klagelieder",                    name: "Klagelieder",           size: 5  },
  { id: "das-buch-baruch",                    name: "Baruch",                size: 6  },
  { id: "das-buch-ezechiel",                  name: "Ezechiel",              size: 48 },
  { id: "das-buch-daniel",                    name: "Daniel",                size: 14 },
  { id: "das-buch-hosea",                     name: "Hosea",                 size: 14 },
  { id: "das-buch-joel",                      name: "Joel",                  size: 3  },
  { id: "das-buch-amos",                      name: "Amos",                  size: 9  },
  { id: "das-buch-obadja",                    name: "Obadja",                size: 1  },
  { id: "das-buch-jona",                      name: "Jona",                  size: 4  },
  { id: "das-buch-micha",                     name: "Micha",                 size: 7  },
  { id: "das-buch-nahum",                     name: "Nahum",                 size: 3  },
  { id: "das-buch-habakuk",                   name: "Habakuk",               size: 3  },
  { id: "das-buch-zefanja",                   name: "Zefanja",               size: 3  },
  { id: "das-buch-haggai",                    name: "Haggai",                size: 2  },
  { id: "das-buch-sacharja",                  name: "Sacharja",              size: 14 },
  { id: "das-buch-maleachi",                  name: "Maleachi",              size: 3  },
  { id: "das-evangelium-nach-matthaus",       name: "Matthäus",              size: 28 },
  { id: "das-evangelium-nach-markus",         name: "Markus",                size: 16 },
  { id: "das-evangelium-nach-lukas",          name: "Lukas",                 size: 24 },
  { id: "das-evangelium-nach-johannes",       name: "Johannes",              size: 21 },
  { id: "die-apostelgeschichte",              name: "Apostelgeschichte",     size: 28 },
  { id: "der-brief-an-die-romer",             name: "Römer",                 size: 16 },
  { id: "der-erste-brief-an-die-korinther",   name: "1. Korinther",          size: 16 },
  { id: "der-zweite-brief-an-die-korinther",  name: "2. Korinther",          size: 13 },
  { id: "der-brief-an-die-galater",           name: "Galater",               size: 6  },
  { id: "der-brief-an-die-epheser",           name: "Epheser",               size: 6  },
  { id: "der-brief-an-die-philipper",         name: "Philipper",             size: 4  },
  { id: "der-brief-an-die-kolosser",          name: "Kolosser",              size: 4  },
  { id: "der-erste-brief-an-die-thessalonicher", name: "1. Thessalonicher",  size: 5  },
  { id: "der-zweite-brief-an-die-thessalonicher", name: "2. Thessalonicher", size: 3  },
  { id: "der-erste-brief-an-timotheus",       name: "1. Timotheus",          size: 6  },
  { id: "der-zweite-brief-an-timotheus",      name: "2. Timotheus",          size: 4  },
  { id: "der-brief-an-titus",                 name: "Titus",                 size: 3  },
  { id: "der-brief-an-philemon",              name: "Philemon",              size: 1  },
  { id: "der-brief-an-die-hebraer",           name: "Hebräer",               size: 13 },
  { id: "der-brief-des-jakobus",              name: "Jakobus",               size: 5  },
  { id: "der-erste-brief-des-petrus",         name: "1. Petrus",             size: 5  },
  { id: "der-zweite-brief-des-petrus",        name: "2. Petrus",             size: 3  },
  { id: "der-erste-brief-des-johannes",       name: "1. Johannes",           size: 5  },
  { id: "der-zweite-brief-des-johannes",      name: "2. Johannes",           size: 1  },
  { id: "der-dritte-brief-des-johannes",      name: "3. Johannes",           size: 1  },
  { id: "der-brief-des-judas",                name: "Judas",                 size: 1  },
  { id: "die-offenbarung-des-johannes",       name: "Offenbarung",           size: 22 }
];
