export const catholicBookIds_it = [
  { id: "genesi",               name: "Genesi",               size: 50 },
  { id: "esodo",                name: "Esodo",                size: 40 },
  { id: "levitico",             name: "Levitico",             size: 27 },
  { id: "numeri",               name: "Numeri",               size: 36 },
  { id: "deuteronomio",         name: "Deuteronomio",         size: 34 },
  { id: "giosue",               name: "Giosuè",               size: 24 },
  { id: "giudici",              name: "Giudici",              size: 21 },
  { id: "rut",                  name: "Rut",                  size: 4  },
  { id: "1-samuele",            name: "1 Samuele",            size: 31 },
  { id: "2-samuele",            name: "2 Samuele",            size: 24 },
  { id: "1-re",                 name: "1 Re",                 size: 22 },
  { id: "2-re",                 name: "2 Re",                 size: 25 },
  { id: "1-cronache",           name: "1 Cronache",           size: 29 },
  { id: "2-cronache",           name: "2 Cronache",           size: 36 },
  { id: "esdra",                name: "Esdra",                size: 10 },
  { id: "neemia",               name: "Neemia",               size: 13 },
  { id: "tobia",                name: "Tobia",                size: 14 },
  { id: "giuditta",             name: "Giuditta",             size: 16 },
  { id: "ester",                name: "Ester",                size: 10 },
  { id: "1-maccabei",           name: "1 Maccabei",           size: 16 },
  { id: "2-maccabei",           name: "2 Maccabei",           size: 15 },
  { id: "giobbe",               name: "Giobbe",               size: 42 },
  { id: "salmi",                name: "Salmi",                size: 150 },
  { id: "proverbi",             name: "Proverbi",             size: 31 },
  { id: "ecclesiaste",          name: "Ecclesiaste",          size: 12 },
  { id: "cantico-dei-cantici",  name: "Cantico dei Cantici",  size: 8  },
  { id: "sapienza",             name: "Sapienza",             size: 19 },
  { id: "siracide",             name: "Siracide",             size: 51 },
  { id: "isaia",                name: "Isaia",                size: 66 },
  { id: "geremia",              name: "Geremia",              size: 52 },
  { id: "lamentazioni",         name: "Lamentazioni",         size: 5  },
  { id: "baruc",                name: "Baruc",                size: 6  },
  { id: "ezechiele",            name: "Ezechiele",            size: 48 },
  { id: "daniele",              name: "Daniele",              size: 14 },
  { id: "osea",                 name: "Osea",                 size: 14 },
  { id: "gioele",               name: "Gioele",               size: 3  },
  { id: "amos",                 name: "Amos",                 size: 9  },
  { id: "abdia",                name: "Abdia",                size: 1  },
  { id: "giona",                name: "Giona",                size: 4  },
  { id: "michea",               name: "Michea",               size: 7  },
  { id: "naum",                 name: "Naum",                 size: 3  },
  { id: "abacuc",               name: "Abacuc",               size: 3  },
  { id: "sofonia",              name: "Sofonia",              size: 3  },
  { id: "aggeo",                name: "Aggeo",                size: 2  },
  { id: "zaccaria",             name: "Zaccaria",             size: 14 },
  { id: "malachia",             name: "Malachia",             size: 3  },
  { id: "matteo",               name: "Matteo",               size: 28 },
  { id: "marco",                name: "Marco",                size: 16 },
  { id: "luca",                 name: "Luca",                 size: 24 },
  { id: "giovanni",             name: "Giovanni",             size: 21 },
  { id: "atti-degli-apostoli",  name: "Atti degli Apostoli",  size: 28 },
  { id: "romani",               name: "Romani",               size: 16 },
  { id: "1-corinzi",            name: "1 Corinzi",            size: 16 },
  { id: "2-corinzi",            name: "2 Corinzi",            size: 13 },
  { id: "galati",               name: "Galati",               size: 6  },
  { id: "efesini",              name: "Efesini",              size: 6  },
  { id: "filippesi",            name: "Filippesi",            size: 4  },
  { id: "colossesi",            name: "Colossesi",            size: 4  },
  { id: "1-tessalonicesi",      name: "1 Tessalonicesi",      size: 5  },
  { id: "2-tessalonicesi",      name: "2 Tessalonicesi",      size: 3  },
  { id: "1-timoteo",            name: "1 Timoteo",            size: 6  },
  { id: "2-timoteo",            name: "2 Timoteo",            size: 4  },
  { id: "tito",                 name: "Tito",                 size: 3  },
  { id: "filemone",             name: "Filemone",             size: 1  },
  { id: "ebrei",                name: "Ebrei",                size: 13 },
  { id: "giacomo",              name: "Giacomo",              size: 5  },
  { id: "1-pietro",             name: "1 Pietro",             size: 5  },
  { id: "2-pietro",             name: "2 Pietro",             size: 3  },
  { id: "1-giovanni",           name: "1 Giovanni",           size: 5  },
  { id: "2-giovanni",           name: "2 Giovanni",           size: 1  },
  { id: "3-giovanni",           name: "3 Giovanni",           size: 1  },
  { id: "giuda",                name: "Giuda",                size: 1  },
  { id: "apocalisse",           name: "Apocalisse",           size: 22 }
];
