export const catholicBookIds_fi = [
  { id: "1-mooseksen-kirja", name: "1. Mooseksen kirja", size: 50 },
  { id: "2-mooseksen-kirja", name: "2. Mooseksen kirja", size: 40 },
  { id: "3-mooseksen-kirja", name: "3. Mooseksen kirja", size: 27 },
  { id: "4-mooseksen-kirja", name: "4. Mooseksen kirja", size: 36 },
  { id: "5-mooseksen-kirja", name: "5. Mooseksen kirja", size: 34 },
  { id: "joosuan-kirja", name: "Joosuan kirja", size: 24 },
  { id: "tuomarien-kirja", name: "Tuomarien kirja", size: 21 },
  { id: "ruut", name: "Ruut", size: 4 },
  { id: "1-samuelin-kirja", name: "1. Samuelin kirja", size: 31 },
  { id: "2-samuelin-kirja", name: "2. Samuelin kirja", size: 24 },
  { id: "1-kuningasten-kirja", name: "1. Kuningasten kirja", size: 22 },
  { id: "2-kuningasten-kirja", name: "2. Kuningasten kirja", size: 25 },
  { id: "1-aikakirja", name: "1. Aikakirja", size: 29 },
  { id: "2-aikakirja", name: "2. Aikakirja", size: 36 },
  { id: "esra", name: "Esra", size: 10 },
  { id: "nehemia", name: "Nehemia", size: 13 },
  { id: "tobian-kirja", name: "Tobian kirja", size: 14 },
  { id: "juditin-kirja", name: "Juditin kirja", size: 16 },
  { id: "ester", name: "Ester", size: 10 },
  { id: "job", name: "Job", size: 42 },
  { id: "psalmit", name: "Psalmit", size: 150 },
  { id: "1-makkabealaisten-kirja", name: "1 Makkabealaisten kirja", size: 16 },
  { id: "2-makkabealaisten-kirja", name: "2 Makkabealaisten kirja", size: 15 },
  { id: "sananlaskut", name: "Sananlaskut", size: 31 },
  { id: "saarnaaja", name: "Saarnaaja", size: 12 },
  { id: "korkea-veisuu", name: "Korkea Veisuu", size: 8 },
  { id: "salomon-viisaus", name: "Salomon viisaus", size: 19 },
  { id: "jesus-sirakin-kirja", name: "Jesus Sirakin kirja", size: 51 },
  { id: "jesaja", name: "Jesaja", size: 66 },
  { id: "jeremia", name: "Jeremia", size: 52 },
  { id: "valitusvirret", name: "Valitusvirret", size: 5 },
  { id: "propheta-baruk", name: "Propheta Baruk", size: 6 },
  { id: "hesekiel", name: "Hesekiel", size: 48 },
  { id: "daniel", name: "Daniel", size: 14 },
  { id: "hoosea", name: "Hoosea", size: 14 },
  { id: "jooel", name: "Jooel", size: 3 },
  { id: "aamos", name: "Aamos", size: 9 },
  { id: "obadja", name: "Obadja", size: 1 },
  { id: "joona", name: "Joona", size: 4 },
  { id: "miika", name: "Miika", size: 7 },
  { id: "naahum", name: "Naahum", size: 3 },
  { id: "habakuk", name: "Habakuk", size: 3 },
  { id: "sefanja", name: "Sefanja", size: 3 },
  { id: "haggai", name: "Haggai", size: 2 },
  { id: "sakarja", name: "Sakarja", size: 14 },
  { id: "malakia", name: "Malakia", size: 3 },
  { id: "matteuksen-evankeliumi", name: "Matteuksen evankeliumi", size: 28 },
  { id: "markuksen-evankeliumi", name: "Markuksen evankeliumi", size: 16 },
  { id: "luukaksen-evankeliumi", name: "Luukaksen evankeliumi", size: 24 },
  { id: "johanneksen-evankeliumi", name: "Johanneksen evankeliumi", size: 21 },
  { id: "apostolien-teot", name: "Apostolien Teot", size: 28 },
  { id: "roomalaisille", name: "Roomalaisille", size: 16 },
  { id: "1korinttolaisille", name: "1.Korinttolaisille", size: 16 },
  { id: "2korinttolaisille", name: "2.Korinttolaisille", size: 13 },
  { id: "galatalaisille", name: "Galatalaisille", size: 6 },
  { id: "efesolaisille", name: "Efesolaisille", size: 6 },
  { id: "filippilaisille", name: "Filippiläisille", size: 4 },
  { id: "kolossalaisille", name: "Kolossalaisille", size: 4 },
  { id: "1-tessalonikalaisille", name: "1. Tessalonikalaisille", size: 5 },
  { id: "2-tessalonikalaisille", name: "2. Tessalonikalaisille", size: 3 },
  { id: "1-timoteukselle", name: "1. Timoteukselle", size: 6 },
  { id: "2-timoteukselle", name: "2. Timoteukselle", size: 4 },
  { id: "tiitukselle", name: "Tiitukselle", size: 3 },
  { id: "filemonille", name: "Filemonille", size: 1 },
  { id: "kirje-hebrealaisille", name: "Kirje hebrealaisille", size: 13 },
  { id: "jaakobin-kirje", name: "Jaakobin kirje", size: 5 },
  { id: "1-pietarin-kirje", name: "1. Pietarin kirje", size: 5 },
  { id: "2-pietarin-kirje", name: "2. Pietarin kirje", size: 3 },
  { id: "1-johanneksen-kirje", name: "1. Johanneksen kirje", size: 5 },
  { id: "2-johanneksen-kirje", name: "2. Johanneksen kirje", size: 1 },
  { id: "3-johanneksen-kirje", name: "3. Johanneksen kirje", size: 1 },
  { id: "juudaan-kirje", name: "Juudaan kirje", size: 1 },
  { id: "johanneksen-ilmestys", name: "Johanneksen ilmestys", size: 22 },
];
