export const catholicBookIds_it = [
  { id: "genesi",                   name: "Genesi",                   size: 50 },
  { id: "esodo",                    name: "Esodo",                    size: 40 },
  { id: "levitico",                 name: "Levitico",                 size: 27 },
  { id: "numeri",                   name: "Numeri",                   size: 36 },
  { id: "deuteronomio",             name: "Deuteronomio",             size: 34 },
  { id: "giosue",                   name: "Giosuè",                   size: 24 },
  { id: "giudici",                  name: "Giudici",                  size: 21 },
  { id: "rut",                      name: "Rut",                      size: 4  },
  { id: "samuele-1",                name: "1 Samuele",                size: 31 },
  { id: "samuele-2",                name: "2 Samuele",                size: 24 },
  { id: "re-1",                     name: "1 Re",                     size: 22 },
  { id: "re-2",                     name: "2 Re",                     size: 25 },
  { id: "cronache-1",               name: "1 Cronache",               size: 29 },
  { id: "cronache-2",               name: "2 Cronache",               size: 36 },
  { id: "esdra",                    name: "Esdra",                    size: 10 },
  { id: "neemia",                   name: "Neemia",                   size: 13 },
  { id: "tobi",                     name: "Tobi",                     size: 14 },
  { id: "giuditta",                 name: "Giuditta",                 size: 16 },
  { id: "ester",                    name: "Ester",                    size: 10 },
  { id: "maccabei-1",               name: "1 Maccabei",               size: 16 },
  { id: "maccabei-2",               name: "2 Maccabei",               size: 15 },
  { id: "giobbe",                   name: "Giobbe",                   size: 42 },
  { id: "salmi",                    name: "Salmi",                    size: 150 },
  { id: "proverbi",                 name: "Proverbi",                 size: 31 },
  { id: "qoelet-ecclesiaste",       name: "Qoelet (Ecclesiaste)",     size: 12 },
  { id: "cantico-dei-cantici",      name: "Cantico dei Cantici",      size: 8  },
  { id: "sapienza",                 name: "Sapienza",                 size: 19 },
  { id: "siracide",                 name: "Siracide",                 size: 51 },
  { id: "isaia",                    name: "Isaia",                    size: 66 },
  { id: "geremia",                  name: "Geremia",                  size: 52 },
  { id: "lamentazioni",             name: "Lamentazioni",             size: 5  },
  { id: "baruc",                    name: "Baruc",                    size: 6  },
  { id: "ezechiele",                name: "Ezechiele",                size: 48 },
  { id: "daniele",                  name: "Daniele",                  size: 14 },
  { id: "osea",                     name: "Osea",                     size: 14 },
  { id: "gioele",                   name: "Gioele",                   size: 3  },
  { id: "amos",                     name: "Amos",                     size: 9  },
  { id: "abdia",                    name: "Abdia",                    size: 1  },
  { id: "giona",                    name: "Giona",                    size: 4  },
  { id: "michea",                   name: "Michea",                   size: 7  },
  { id: "nahum",                    name: "Nahum",                    size: 3  },
  { id: "abacuc",                   name: "Abacuc",                   size: 3  },
  { id: "sofonia",                  name: "Sofonia",                  size: 3  },
  { id: "aggeo",                    name: "Aggeo",                    size: 2  },
  { id: "zaccaria",                 name: "Zaccaria",                 size: 14 },
  { id: "malachia",                 name: "Malachia",                 size: 3  },
  { id: "vangelo-secondo-matteo",   name: "Vangelo secondo Matteo",   size: 28 },
  { id: "vangelo-secondo-marco",    name: "Vangelo secondo Marco",    size: 16 },
  { id: "vangelo-secondo-luca",     name: "Vangelo secondo Luca",     size: 24 },
  { id: "vangelo-secondo-giovanni", name: "Vangelo secondo Giovanni", size: 21 },
  { id: "atti-degli-apostoli",      name: "Atti degli Apostoli",      size: 28 },
  { id: "romani",                   name: "Romani",                   size: 16 },
  { id: "corinzi-1",                name: "1 Corinzi",                size: 16 },
  { id: "corinzi-2",                name: "2 Corinzi",                size: 13 },
  { id: "galati",                   name: "Galati",                   size: 6  },
  { id: "efesini",                  name: "Efesini",                  size: 6  },
  { id: "filippesi",                name: "Filippesi",                size: 4  },
  { id: "colossesi",                name: "Colossesi",                size: 4  },
  { id: "tessalonicesi-1",          name: "1 Tessalonicesi",          size: 5  },
  { id: "tessalonicesi-2",          name: "2 Tessalonicesi",          size: 3  },
  { id: "timoteo-1",                name: "1 Timoteo",                size: 6  },
  { id: "timoteo-2",                name: "2 Timoteo",                size: 4  },
  { id: "tito",                     name: "Tito",                     size: 3  },
  { id: "filemone",                 name: "Filemone",                 size: 1  },
  { id: "ebrei",                    name: "Ebrei",                    size: 13 },
  { id: "giacomo",                  name: "Giacomo",                  size: 5  },
  { id: "pietro-1",                 name: "1 Pietro",                 size: 5  },
  { id: "pietro-2",                 name: "2 Pietro",                 size: 3  },
  { id: "giovanni-1",               name: "1 Giovanni",               size: 5  },
  { id: "giovanni-2",               name: "2 Giovanni",               size: 1  },
  { id: "giovanni-3",               name: "3 Giovanni",               size: 1  },
  { id: "giuda",                    name: "Giuda",                    size: 1  },
  { id: "apocalisse",               name: "Apocalisse",               size: 22 }
];
