export const catholicBookIds_es = [
  { id: "genesis",                      name: "Génesis",                       size: 50 },
  { id: "exodo",                        name: "Éxodo",                         size: 40 },
  { id: "levitico",                     name: "Levítico",                      size: 27 },
  { id: "numeros",                      name: "Números",                       size: 36 },
  { id: "deuteronomio",                 name: "Deuteronomio",                  size: 34 },
  { id: "josue",                        name: "Josué",                         size: 24 },
  { id: "jueces",                       name: "Jueces",                        size: 21 },
  { id: "rut",                          name: "Rut",                           size: 4  },
  { id: "1-samuel",                     name: "1 Samuel",                      size: 31 },
  { id: "2-samuel",                     name: "2 Samuel",                      size: 24 },
  { id: "1-reyes",                      name: "1 Reyes",                       size: 22 },
  { id: "2-reyes",                      name: "2 Reyes",                       size: 25 },
  { id: "1-cronicas",                   name: "1 Crónicas",                    size: 29 },
  { id: "2-cronicas",                   name: "2 Crónicas",                    size: 36 },
  { id: "esdras",                       name: "Esdras",                        size: 10 },
  { id: "nehemias",                     name: "Nehemías",                      size: 13 },
  { id: "tobias",                       name: "Tobías",                        size: 14 },
  { id: "judit",                        name: "Judit",                         size: 16 },
  { id: "ester",                        name: "Ester",                         size: 10 },
  { id: "1-macabeos",                   name: "1 Macabeos",                    size: 16 },
  { id: "2-macabeos",                   name: "2 Macabeos",                    size: 15 },
  { id: "job",                          name: "Job",                           size: 42 },
  { id: "salmos",                       name: "Salmos",                        size: 150 },
  { id: "proverbios",                   name: "Proverbios",                    size: 31 },
  { id: "eclesiastes-qohelet",          name: "Eclesiastés (Qohelet)",         size: 12 },
  { id: "cantar",                       name: "Cantar",                        size: 8  },
  { id: "sabiduria",                    name: "Sabiduría",                     size: 19 },
  { id: "siracides-eclesiastico",       name: "Sirácides (Eclesiástico)",      size: 51 },
  { id: "isaias",                       name: "Isaías",                        size: 66 },
  { id: "jeremias",                     name: "Jeremías",                      size: 52 },
  { id: "lamentaciones",                name: "Lamentaciones",                 size: 5  },
  { id: "baruc",                        name: "Baruc",                         size: 6  },
  { id: "ezequiel",                     name: "Ezequiel",                      size: 48 },
  { id: "daniel",                       name: "Daniel",                        size: 14 },
  { id: "oseas",                        name: "Oseas",                         size: 14 },
  { id: "joel",                         name: "Joel",                          size: 3  },
  { id: "amos",                         name: "Amós",                          size: 9  },
  { id: "abdias",                       name: "Abdías",                        size: 1  },
  { id: "jonas",                        name: "Jonás",                         size: 4  },
  { id: "miqueas",                      name: "Miqueas",                       size: 7  },
  { id: "nahun",                        name: "Nahún",                         size: 3  },
  { id: "habacuc",                      name: "Habacuc",                       size: 3  },
  { id: "sofonias",                     name: "Sofonías",                      size: 3  },
  { id: "ageo",                         name: "Ageo",                          size: 2  },
  { id: "zacarias",                     name: "Zacarías",                      size: 14 },
  { id: "malaquias",                    name: "Malaquías",                     size: 3  },
  { id: "evangelio-segun-san-mateo",    name: "Evangelio según San Mateo",     size: 28 },
  { id: "evangelio-segun-san-marcos",   name: "Evangelio según San Marcos",    size: 16 },
  { id: "evangelio-segun-san-lucas",    name: "Evangelio según San Lucas",     size: 24 },
  { id: "evangelio-segun-san-juan",     name: "Evangelio según San Juan",      size: 21 },
  { id: "hecho-de-los-apostoles",       name: "Hecho de los Apóstoles",        size: 28 },
  { id: "carta-a-los-romanos",          name: "Carta a los Romanos",           size: 16 },
  { id: "1-carta-a-los-corintios",      name: "1º Carta a los Corintios",      size: 16 },
  { id: "2-carta-a-los-corintios",      name: "2º Carta a los Corintios",      size: 13 },
  { id: "carta-a-los-galatas",          name: "Carta a los Gálatas",           size: 6  },
  { id: "carta-a-los-efesios",          name: "Carta a los Efesios",           size: 6  },
  { id: "carta-a-los-filipenses",       name: "Carta a los Filipenses",        size: 4  },
  { id: "carta-a-los-colosenses",       name: "Carta a los Colosenses",        size: 4  },
  { id: "1-carta-a-los-tesalonicenses", name: "1º Carta a los Tesalonicenses", size: 5  },
  { id: "2-carta-a-los-tesalonicenses", name: "2º Carta a los Tesalonicenses", size: 3  },
  { id: "1-carta-a-timoteo",            name: "1º Carta a Timoteo",            size: 6  },
  { id: "2-carta-a-timoteo",            name: "2º Carta a Timoteo",            size: 4  },
  { id: "carta-a-tito",                 name: "Carta a Tito",                  size: 3  },
  { id: "carta-a-filemon",              name: "Carta a Filemón",               size: 1  },
  { id: "carta-a-los-hebreos",          name: "Carta a los Hebreos",           size: 13 },
  { id: "carta-de-santiago",            name: "Carta de Santiago",             size: 5  },
  { id: "1-carta-de-pedro",             name: "1º Carta de Pedro",             size: 5  },
  { id: "2-carta-de-pedro",             name: "2º Carta de Pedro",             size: 3  },
  { id: "1-carta-de-juan",              name: "1º Carta de Juan",              size: 5  },
  { id: "2-carta-de-juan",              name: "2º Carta de Juan",              size: 1  },
  { id: "3-carta-de-juan",              name: "3º Carta de Juan",              size: 1  },
  { id: "carta-de-judas",               name: "Carta de Judas",                size: 1  },
  { id: "apocalipsis",                  name: "Apocalipsis",                   size: 22 }
];
