export const catholicBookIds_es = [
  { id: "genesis",                  name: "Génesis",                  size: 50 },
  { id: "exodo",                    name: "Éxodo",                    size: 40 },
  { id: "levitico",                 name: "Levítico",                 size: 27 },
  { id: "numeros",                  name: "Números",                  size: 36 },
  { id: "deuteronomio",             name: "Deuteronomio",             size: 34 },
  { id: "josue",                    name: "Josué",                    size: 24 },
  { id: "jueces",                   name: "Jueces",                   size: 21 },
  { id: "rut",                      name: "Rut",                      size: 4  },
  { id: "i-samuel",                 name: "I Samuel",                 size: 31 },
  { id: "ii-samuel",                name: "II Samuel",                size: 24 },
  { id: "i-reyes",                  name: "I Reyes",                  size: 22 },
  { id: "ii-reyes",                 name: "II Reyes",                 size: 25 },
  { id: "i-cronicas",               name: "I Crónicas",               size: 29 },
  { id: "ii-cronicas",              name: "II Crónicas",              size: 36 },
  { id: "esdras",                   name: "Esdras",                   size: 10 },
  { id: "nehemias",                 name: "Nehemías",                 size: 13 },
  { id: "tobias",                   name: "Tobías",                   size: 14 },
  { id: "judit",                    name: "Judit",                    size: 16 },
  { id: "ester",                    name: "Ester",                    size: 10 },
  { id: "i-macabeos",               name: "I Macabeos",               size: 16 },
  { id: "ii-macabeos",              name: "II Macabeos",              size: 15 },
  { id: "job",                      name: "Job",                      size: 42 },
  { id: "salmos",                   name: "Salmos",                   size: 150 },
  { id: "proverbios",               name: "Proverbios",               size: 31 },
  { id: "eclesiastes",              name: "Eclesiastés",              size: 12 },
  { id: "cantar",   name: "Cantar de los Cantares",   size: 8  },
  { id: "sabiduria",                name: "Sabiduría",                size: 19 },
  { id: "eclesiastico",             name: "Eclesiástico",             size: 51 },
  { id: "isaias",                   name: "Isaías",                   size: 66 },
  { id: "jeremias",                 name: "Jeremías",                 size: 52 },
  { id: "lamentaciones",            name: "Lamentaciones",            size: 5  },
  { id: "baruc",                    name: "Baruc",                    size: 6  },
  { id: "ezequiel",                 name: "Ezequiel",                 size: 48 },
  { id: "daniel",                   name: "Daniel",                   size: 14 },
  { id: "oseas",                    name: "Oseas",                    size: 14 },
  { id: "joel",                     name: "Joel",                     size: 3  },
  { id: "amos",                     name: "Amós",                     size: 9  },
  { id: "abdias",                   name: "Abdías",                   size: 1  },
  { id: "jonas",                    name: "Jonás",                    size: 4  },
  { id: "miqueas",                  name: "Miqueas",                  size: 7  },
  { id: "nahun",                    name: "Nahún",                    size: 3  },
  { id: "habacuc",                  name: "Habacuc",                  size: 3  },
  { id: "sofonias",                 name: "Sofonías",                 size: 3  },
  { id: "ageo",                     name: "Ageo",                     size: 2  },
  { id: "zacarias",                 name: "Zacarías",                 size: 14 },
  { id: "malaquias",                name: "Malaquías",                size: 3  },
  { id: "mateo",                    name: "Mateo",                    size: 28 },
  { id: "marcos",                   name: "Marcos",                   size: 16 },
  { id: "lucas",                    name: "Lucas",                    size: 24 },
  { id: "juan",                     name: "Juan",                     size: 21 },
  { id: "hechos",                   name: "Hechos",                   size: 28 },
  { id: "romanos",                  name: "Romanos",                  size: 16 },
  { id: "i-corintios",              name: "I Corintios",              size: 16 },
  { id: "ii-corintios",             name: "II Corintios",             size: 13 },
  { id: "galatas",                  name: "Gálatas",                  size: 6  },
  { id: "efesios",                  name: "Efesios",                  size: 6  },
  { id: "filipenses",               name: "Filipenses",               size: 4  },
  { id: "colosenses",               name: "Colosenses",               size: 4  },
  { id: "i-tesalonicenses",         name: "I Tesalonicenses",         size: 5  },
  { id: "ii-tesalonicenses",        name: "II Tesalonicenses",        size: 3  },
  { id: "i-timoteo",                name: "I Timoteo",                size: 6  },
  { id: "ii-timoteo",               name: "II Timoteo",               size: 4  },
  { id: "tito",                     name: "Tito",                     size: 3  },
  { id: "filemon",                  name: "Filemón",                  size: 1  },
  { id: "hebreos",                  name: "Hebreos",                  size: 13 },
  { id: "santiago",                 name: "Santiago",                 size: 5  },
  { id: "i-pedro",                  name: "I Pedro",                  size: 5  },
  { id: "ii-pedro",                 name: "II Pedro",                 size: 3  },
  { id: "i-juan",                   name: "I Juan",                   size: 5  },
  { id: "ii-juan",                  name: "II Juan",                  size: 1  },
  { id: "iii-juan",                 name: "III Juan",                 size: 1  },
  { id: "judas",                    name: "Judas",                    size: 1  },
  { id: "apocalipsis",              name: "Apocalipsis",              size: 22 }
];
