export const catholicBookIds_la = [
  { id: "liber-genesis",              name: "Liber Genesis",               size: 50 },
  { id: "liber-exodus",               name: "Liber Exodus",                size: 40 },
  { id: "liber-leviticus",            name: "Liber Leviticus",             size: 27 },
  { id: "liber-numeri",               name: "Liber Numeri",                size: 36 },
  { id: "liber-deuteronomii",         name: "Liber Deuteronomii",          size: 34 },
  { id: "liber-iosue",                name: "Liber Iosue",                 size: 24 },
  { id: "liber-iudicum",              name: "Liber Iudicum",               size: 21 },
  { id: "liber-ruth",                 name: "Liber Ruth",                  size: 4  },
  { id: "liber-i-samuelis",           name: "Liber I Samuelis",            size: 31 },
  { id: "liber-ii-samuelis",          name: "Liber II Samuelis",           size: 24 },
  { id: "liber-i-regum",              name: "Liber I Regum",               size: 22 },
  { id: "liber-ii-regum",             name: "Liber II Regum",              size: 25 },
  { id: "liber-i-paralipomenon",      name: "Liber I Paralipomenon",       size: 29 },
  { id: "liber-ii-paralipomenon",     name: "Liber II Paralipomenon",      size: 36 },
  { id: "liber-esdrae",               name: "Liber Esdrae",                size: 10 },
  { id: "liber-nehemiae",             name: "Liber Nehemiae",              size: 13 },
  { id: "liber-thobis",               name: "Liber Thobis",                size: 14 },
  { id: "liber-iudith",               name: "Liber Iudith",                size: 16 },
  { id: "liber-esther",               name: "Liber Esther",                size: 16 },
  { id: "liber-iob",                  name: "Liber Iob",                   size: 42 },
  { id: "liber-psalmorum",            name: "Liber Psalmorum",             size: 150 },
  { id: "liber-i-maccabaeorum",       name: "Liber I Maccabaeorum",        size: 16 },
  { id: "liber-ii-maccabaeorum",      name: "Liber II Maccabaeorum",       size: 15 },
  { id: "liber-proverbiorum",         name: "Liber Proverbiorum",          size: 31 },
  { id: "liber-ecclesiastes",         name: "Liber Ecclesiastes",          size: 12 },
  { id: "canticum-canticorum",        name: "Canticum Canticorum",         size: 8  },
  { id: "liber-sapientiae",           name: "Liber Sapientiae",            size: 19 },
  { id: "liber-ecclesiasticus",       name: "Liber Ecclesiasticus",        size: 51 },
  { id: "liber-isaiae",               name: "Liber Isaiae",                size: 66 },
  { id: "liber-ieremiae",             name: "Liber Ieremiae",              size: 52 },
  { id: "lamentationes",              name: "Lamentationes",               size: 5  },
  { id: "liber-baruch",               name: "Liber Baruch",                size: 6  },
  { id: "prophetia-ezechielis",       name: "Prophetia Ezechielis",        size: 48 },
  { id: "prophetia-danielis",         name: "Prophetia Danielis",          size: 14 },
  { id: "prophetia-osee",             name: "Prophetia Osee",              size: 14 },
  { id: "prophetia-ioel",             name: "Prophetia Ioel",              size: 3  },
  { id: "prophetia-amos",             name: "Prophetia Amos",              size: 9  },
  { id: "prophetia-abdiae",           name: "Prophetia Abdiae",            size: 1  },
  { id: "prophetia-ionae",            name: "Prophetia Ionae",             size: 4  },
  { id: "prophetia-michaeae",         name: "Prophetia Michaeae",          size: 7  },
  { id: "prophetia-nahum",            name: "Prophetia Nahum",             size: 3  },
  { id: "prophetia-habacuc",          name: "Prophetia Habacuc",           size: 3  },
  { id: "prophetia-sophoniae",        name: "Prophetia Sophoniae",         size: 3  },
  { id: "prophetia-aggaei",           name: "Prophetia Aggaei",            size: 2  },
  { id: "prophetia-zachariae",        name: "Prophetia Zachariae",         size: 14 },
  { id: "prophetia-malachiae",        name: "Prophetia Malachiae",         size: 3  },
  { id: "evangelium-secundum-matthaeum", name: "Evangelium secundum Matthaeum", size: 28 },
  { id: "evangelium-secundum-marcum",    name: "Evangelium secundum Marcum",    size: 16 },
  { id: "evangelium-secundum-lucam",     name: "Evangelium secundum Lucam",     size: 24 },
  { id: "evangelium-secundum-ioannem",   name: "Evangelium secundum Ioannem",   size: 21 },
  { id: "actus-apostolorum",             name: "Actus Apostolorum",             size: 28 },
  { id: "epistula-ad-romanos",           name: "Epistula ad Romanos",           size: 16 },
  { id: "epistula-i-ad-corinthios",      name: "Epistula I ad Corinthios",      size: 16 },
  { id: "epistula-ii-ad-corinthios",     name: "Epistula II ad Corinthios",     size: 13 },
  { id: "epistula-ad-galatas",           name: "Epistula ad Galatas",           size: 6  },
  { id: "epistula-ad-ephesios",          name: "Epistula ad Ephesios",          size: 6  },
  { id: "epistula-ad-philippenses",      name: "Epistula ad Philippenses",      size: 4  },
  { id: "epistula-ad-colossenses",       name: "Epistula ad Colossenses",       size: 4  },
  { id: "epistula-i-ad-thessalonicenses", name: "Epistula I ad Thessalonicenses", size: 5  },
  { id: "epistula-ii-ad-thessalonicenses", name: "Epistula II ad Thessalonicenses", size: 3  },
  { id: "epistula-i-ad-timotheum",       name: "Epistula I ad Timotheum",       size: 6  },
  { id: "epistula-ii-ad-timotheum",      name: "Epistula II ad Timotheum",      size: 4  },
  { id: "epistula-ad-titum",             name: "Epistula ad Titum",             size: 3  },
  { id: "epistulam-ad-philemonem",       name: "Epistulam ad Philemonem",       size: 1  },
  { id: "epistula-ad-hebraeos",          name: "Epistula ad Hebraeos",          size: 13 },
  { id: "epistula-iacobi",               name: "Epistula Iacobi",               size: 5  },
  { id: "epistula-i-petri",              name: "Epistula I Petri",              size: 5  },
  { id: "epistula-ii-petri",             name: "Epistula II Petri",             size: 3  },
  { id: "epistula-i-ioannis",            name: "Epistula I Ioannis",            size: 5  },
  { id: "epistula-ii-ioannis",           name: "Epistula II Ioannis",           size: 1  },
  { id: "epistula-iii-ioannis",          name: "Epistula III Ioannis",          size: 1  },
  { id: "epistula-iudae",                name: "Epistula Iudae",                size: 1  },
  { id: "apocalypsis-ioannis",           name: "Apocalypsis Ioannis",           size: 22 }
];
