export const catholicBookIds_de = [
  { id: "das-buch-genesis",     name: "Genesis",              size: 50 },
  { id: "das-buch-exodus",      name: "Exodus",               size: 40 },
  { id: "das-buch-levitikus",   name: "Levitikus",            size: 27 },
  { id: "das-buch-numeri",      name: "Numeri",               size: 36 },
  { id: "das-buch-deuteronomium", name: "Deuteronomium",      size: 34 },
  { id: "josua",                name: "Josua",                size: 24 },
  { id: "richter",              name: "Richter",              size: 21 },
  { id: "rut",                  name: "Rut",                  size: 4  },
  { id: "1-samuel",             name: "1. Samuel",            size: 31 },
  { id: "2-samuel",             name: "2. Samuel",            size: 24 },
  { id: "1-konige",             name: "1. Könige",            size: 22 },
  { id: "2-konige",             name: "2. Könige",            size: 25 },
  { id: "1-chronik",            name: "1. Chronik",           size: 29 },
  { id: "2-chronik",            name: "2. Chronik",           size: 36 },
  { id: "esra",                 name: "Esra",                 size: 10 },
  { id: "nehemia",              name: "Nehemia",              size: 13 },
  { id: "tobit",                name: "Tobit",                size: 14 },
  { id: "judit",                name: "Judit",                size: 16 },
  { id: "ester",                name: "Ester",                size: 10 },
  { id: "1-makkabaer",          name: "1. Makkabäer",         size: 16 },
  { id: "2-makkabaer",          name: "2. Makkabäer",         size: 15 },
  { id: "iob",                  name: "Iob",                  size: 42 },
  { id: "psalmen",              name: "Psalmen",              size: 150 },
  { id: "spruche",              name: "Sprüche",              size: 31 },
  { id: "kohelet",              name: "Kohelet",              size: 12 },
  { id: "hohelied",             name: "Hohelied",             size: 8  },
  { id: "weisheit",             name: "Weisheit",             size: 19 },
  { id: "sirach",               name: "Sirach",               size: 51 },
  { id: "jesaja",               name: "Jesaja",               size: 66 },
  { id: "jeremia",              name: "Jeremia",              size: 52 },
  { id: "klagelieder",          name: "Klagelieder",          size: 5  },
  { id: "baruch",               name: "Baruch",               size: 6  },
  { id: "ezechiel",             name: "Ezechiel",             size: 48 },
  { id: "daniel",               name: "Daniel",               size: 14 },
  { id: "hosea",                name: "Hosea",                size: 14 },
  { id: "joel",                 name: "Joel",                 size: 3  },
  { id: "amos",                 name: "Amos",                 size: 9  },
  { id: "obadja",               name: "Obadja",               size: 1  },
  { id: "jona",                 name: "Jona",                 size: 4  },
  { id: "micha",                name: "Micha",                size: 7  },
  { id: "nahum",                name: "Nahum",                size: 3  },
  { id: "habakuk",              name: "Habakuk",              size: 3  },
  { id: "zefanja",              name: "Zefanja",              size: 3  },
  { id: "haggai",               name: "Haggai",               size: 2  },
  { id: "sacharja",             name: "Sacharja",             size: 14 },
  { id: "maleachi",             name: "Maleachi",             size: 3  },
  { id: "matthaus",             name: "Matthäus",             size: 28 },
  { id: "markus",               name: "Markus",                size: 16 },
  { id: "lukas",                name: "Lukas",                 size: 24 },
  { id: "johannes",             name: "Johannes",              size: 21 },
  { id: "apostelgeschichte",    name: "Apostelgeschichte",     size: 28 },
  { id: "romer",                name: "Römer",                 size: 16 },
  { id: "1-korinther",          name: "1. Korinther",          size: 16 },
  { id: "2-korinther",          name: "2. Korinther",          size: 13 },
  { id: "galater",              name: "Galater",               size: 6  },
  { id: "epheser",              name: "Epheser",               size: 6  },
  { id: "philipper",            name: "Philipper",             size: 4  },
  { id: "kolosser",             name: "Kolosser",              size: 4  },
  { id: "1-thessalonicher",     name: "1. Thessalonicher",     size: 5  },
  { id: "2-thessalonicher",     name: "2. Thessalonicher",     size: 3  },
  { id: "1-timotheus",          name: "1. Timotheus",          size: 6  },
  { id: "2-timotheus",          name: "2. Timotheus",          size: 4  },
  { id: "titus",                name: "Titus",                 size: 3  },
  { id: "philemon",             name: "Philemon",              size: 1  },
  { id: "hebraer",              name: "Hebräer",               size: 13 },
  { id: "jakobus",              name: "Jakobus",               size: 5  },
  { id: "1-petrus",             name: "1. Petrus",             size: 5  },
  { id: "2-petrus",             name: "2. Petrus",             size: 3  },
  { id: "1-johannes",           name: "1. Johannes",           size: 5  },
  { id: "2-johannes",           name: "2. Johannes",           size: 1  },
  { id: "3-johannes",           name: "3. Johannes",           size: 1  },
  { id: "judas",                name: "Judas",                 size: 1  },
  { id: "offenbarung",          name: "Offenbarung",           size: 22 }
];
