export const catholicBookIds_hr = [
  { id: "knjiga-postanka", name: "Knjiga Postanka", size: 50 },
  { id: "knjiga-izlaska", name: "Knjiga Izlaska", size: 40 },
  { id: "levitski-zakonik", name: "Levitski zakonik", size: 27 },
  { id: "knjiga-brojeva", name: "Knjiga Brojeva", size: 36 },
  { id: "ponovljeni-zakon", name: "Ponovljeni zakon", size: 34 },
  { id: "josua", name: "Jošua", size: 24 },
  { id: "knjiga-o-sucima", name: "Knjiga o sucima", size: 21 },
  { id: "knjiga-o-ruti", name: "Knjiga o Ruti", size: 4 },
  { id: "prva-knjiga-o-samuelu", name: "Prva knjiga o Samuelu", size: 31 },
  { id: "druga-knjiga-o-samuelu", name: "Druga knjiga o Samuelu", size: 24 },
  { id: "prva-knjiga-o-kraljevima", name: "Prva knjiga o kraljevima", size: 22 },
  { id: "druga-knjiga-o-kraljevima", name: "Druga knjiga o kraljevima", size: 25 },
  { id: "prva-knjiga-ljetopisa", name: "Prva knjiga Ljetopisa", size: 29 },
  { id: "druga-knjiga-ljetopisa", name: "Druga knjiga Ljetopisa", size: 36 },
  { id: "knjiga-ezrina", name: "Knjiga Ezrina", size: 10 },
  { id: "knjiga-nehemijina", name: "Knjiga Nehemijina", size: 13 },
  { id: "tobija", name: "Tobija", size: 14 },
  { id: "judita", name: "Judita", size: 16 },
  { id: "estera", name: "Estera", size: 10 },
  { id: "knjiga-o-jobu", name: "Knjiga o Jobu", size: 42 },
  { id: "psalmi", name: "Psalmi", size: 150 },
  { id: "prva-knjiga-o-makabejcima", name: "Prva knjiga o Makabejcima", size: 16 },
  { id: "druga-knjiga-o-makabejcima", name: "Druga knjiga o Makabejcima", size: 15 },
  { id: "mudre-izreke", name: "Mudre izreke", size: 31 },
  { id: "propovjednik", name: "Propovjednik", size: 12 },
  { id: "pjesma-nad-pjesmama", name: "Pjesma nad pjesmama", size: 8 },
  { id: "knjiga-mudrosti", name: "Knjiga Mudrosti", size: 19 },
  { id: "knjiga-sirahova", name: "Knjiga Sirahova", size: 51 },
  { id: "izaija", name: "Izaija", size: 66 },
  { id: "jeremija", name: "Jeremija", size: 52 },
  { id: "tuzaljke", name: "Tužaljke", size: 5 },
  { id: "baruh", name: "Baruh", size: 6 },
  { id: "ezekiel", name: "Ezekiel", size: 48 },
  { id: "daniel", name: "Daniel", size: 14 },
  { id: "hosea", name: "Hošea", size: 14 },
  { id: "joel", name: "Joel", size: 3 },
  { id: "amos", name: "Amos", size: 9 },
  { id: "obadija", name: "Obadija", size: 1 },
  { id: "jona", name: "Jona", size: 4 },
  { id: "mihej", name: "Mihej", size: 7 },
  { id: "nahum", name: "Nahum", size: 3 },
  { id: "habakuk", name: "Habakuk", size: 3 },
  { id: "sefanija", name: "Sefanija", size: 3 },
  { id: "hagaj", name: "Hagaj", size: 2 },
  { id: "zaharija", name: "Zaharija", size: 14 },
  { id: "malahija", name: "Malahija", size: 3 },
  { id: "evanelje-po-mateju", name: "Evanðelje po Mateju", size: 28 },
  { id: "evanelje-po-marku", name: "Evanðelje po Marku", size: 16 },
  { id: "evanelje-po-luki", name: "Evanðelje po Luki", size: 24 },
  { id: "evanelje-po-ivanu", name: "Evanðelje po Ivanu", size: 21 },
  { id: "djela-apostolska", name: "Djela apostolska", size: 28 },
  { id: "poslanica-rimljanima", name: "Poslanica Rimljanima", size: 16 },
  { id: "prva-poslanica-korinaeanima", name: "Prva poslanica Korinæanima", size: 16 },
  { id: "druga-poslanica-korinaeanima", name: "Druga poslanica Korinæanima", size: 13 },
  { id: "poslanica-galaaeanima", name: "Poslanica Galaæanima", size: 6 },
  { id: "poslanica-efezanima", name: "Poslanica Efežanima", size: 6 },
  { id: "poslanica-filipljanima", name: "Poslanica Filipljanima", size: 4 },
  { id: "poslanica-kolosanima", name: "Poslanica Kološanima", size: 4 },
  { id: "prva-poslanica-solunjanima", name: "Prva poslanica Solunjanima", size: 5 },
  { id: "druga-poslanica-solunjanima", name: "Druga poslanica Solunjanima", size: 3 },
  { id: "prva-poslanica-timoteju", name: "Prva poslanica Timoteju", size: 6 },
  { id: "druga-poslanica-timoteju", name: "Druga poslanica Timoteju", size: 4 },
  { id: "poslanica-titu", name: "Poslanica Titu", size: 3 },
  { id: "poslanica-filemonu", name: "Poslanica Filemonu", size: 1 },
  { id: "poslanica-hebrejima", name: "Poslanica Hebrejima", size: 13 },
  { id: "jakovljeva-poslanica", name: "Jakovljeva poslanica", size: 5 },
  { id: "prva-petrova-poslanica", name: "Prva Petrova poslanica", size: 5 },
  { id: "druga-petrova-poslanica", name: "Druga Petrova poslanica", size: 3 },
  { id: "prva-ivanova-poslanica", name: "Prva Ivanova poslanica", size: 5 },
  { id: "druga-ivanova-poslanica", name: "Druga Ivanova poslanica", size: 1 },
  { id: "treaea-ivanova-poslanica", name: "Treæa Ivanova poslanica", size: 1 },
  { id: "poslanica-jude-apostola", name: "Poslanica Jude apostola", size: 1 },
  { id: "otkrivenje", name: "Otkrivenje", size: 22 },
];
