export const catholicBookIds_en = [
  { id: "genesis",              name: "Genesis",              size: 50 },
  { id: "exodus",               name: "Exodus",               size: 40 },
  { id: "leviticus",            name: "Leviticus",            size: 27 },
  { id: "numbers",              name: "Numbers",              size: 36 },
  { id: "deuteronomy",          name: "Deuteronomy",          size: 34 },
  { id: "joshua",               name: "Joshua",               size: 24 },
  { id: "judges",               name: "Judges",               size: 21 },
  { id: "ruth",                 name: "Ruth",                 size: 4  },
  { id: "1-samuel",             name: "1 Samuel",             size: 31 },
  { id: "2-samuel",             name: "2 Samuel",             size: 24 },
  { id: "1-kings",              name: "1 Kings",              size: 22 },
  { id: "2-kings",              name: "2 Kings",              size: 25 },
  { id: "1-chronicles",         name: "1 Chronicles",         size: 29 },
  { id: "2-chronicles",         name: "2 Chronicles",         size: 36 },
  { id: "ezra",                 name: "Ezra",                 size: 10 },
  { id: "nehemiah",             name: "Nehemiah",             size: 13 },
  { id: "tobit",                name: "Tobit",                size: 14 },
  { id: "judith",               name: "Judith",               size: 16 },
  { id: "esther",               name: "Esther",               size: 10 },
  { id: "1-maccabees",          name: "1 Maccabees",          size: 16 },
  { id: "2-maccabees",          name: "2 Maccabees",          size: 15 },
  { id: "job",                  name: "Job",                  size: 42 },
  { id: "psalms",               name: "Psalms",               size: 150 },
  { id: "proverbs",             name: "Proverbs",             size: 31 },
  { id: "ecclesiastes",         name: "Ecclesiastes",         size: 12 },
  { id: "song-of-solomon",      name: "Song of Solomon",      size: 8  },
  { id: "wisdom-of-solomon",    name: "Wisdom of Solomon",    size: 19 },
  { id: "ecclesiasticus",       name: "Ecclesiasticus",       size: 51 },
  { id: "isaiah",               name: "Isaiah",               size: 66 },
  { id: "jeremiah",             name: "Jeremiah",             size: 52 },
  { id: "lamentations",         name: "Lamentations",         size: 5  },
  { id: "baruch",               name: "Baruch",               size: 6  },
  { id: "ezekiel",              name: "Ezekiel",              size: 48 },
  { id: "daniel",               name: "Daniel",               size: 14 },
  { id: "hosea",                name: "Hosea",                size: 14 },
  { id: "joel",                 name: "Joel",                 size: 3  },
  { id: "amos",                 name: "Amos",                 size: 9  },
  { id: "obadiah",              name: "Obadiah",              size: 1  },
  { id: "jonah",                name: "Jonah",                size: 4  },
  { id: "micah",                name: "Micah",                size: 7  },
  { id: "nahum",                name: "Nahum",                size: 3  },
  { id: "habakkuk",             name: "Habakkuk",             size: 3  },
  { id: "zephaniah",            name: "Zephaniah",            size: 3  },
  { id: "haggai",               name: "Haggai",               size: 2  },
  { id: "zechariah",            name: "Zechariah",            size: 14 },
  { id: "malachi",              name: "Malachi",              size: 3  },
  { id: "matthew",              name: "Matthew",              size: 28 },
  { id: "mark",                 name: "Mark",                 size: 16 },
  { id: "luke",                 name: "Luke",                 size: 24 },
  { id: "john",                 name: "John",                 size: 21 },
  { id: "acts",                 name: "Acts",                 size: 28 },
  { id: "romans",               name: "Romans",               size: 16 },
  { id: "1-corinthians",        name: "1 Corinthians",        size: 16 },
  { id: "2-corinthians",        name: "2 Corinthians",        size: 13 },
  { id: "galatians",            name: "Galatians",            size: 6  },
  { id: "ephesians",            name: "Ephesians",            size: 6  },
  { id: "philippians",          name: "Philippians",          size: 4  },
  { id: "colossians",           name: "Colossians",           size: 4  },
  { id: "1-thessalonians",      name: "1 Thessalonians",      size: 5  },
  { id: "2-thessalonians",      name: "2 Thessalonians",      size: 3  },
  { id: "1-timothy",            name: "1 Timothy",            size: 6  },
  { id: "2-timothy",            name: "2 Timothy",            size: 4  },
  { id: "titus",                name: "Titus",                size: 3  },
  { id: "philemon",             name: "Philemon",             size: 1  },
  { id: "hebrews",              name: "Hebrews",              size: 13 },
  { id: "james",                name: "James",                size: 5  },
  { id: "1-peter",              name: "1 Peter",              size: 5  },
  { id: "2-peter",              name: "2 Peter",              size: 3  },
  { id: "1-john",               name: "1 John",               size: 5  },
  { id: "2-john",               name: "2 John",               size: 1  },
  { id: "3-john",               name: "3 John",               size: 1  },
  { id: "jude",                 name: "Jude",                 size: 1  },
  { id: "revelation",           name: "Revelation",           size: 22 }
];
