export const catholicBookIds_ptbr = [
  { id: "genesis",              name: "Gênesis",              size: 50 },
  { id: "exodo",                name: "Êxodo",                size: 40 },
  { id: "levitico",             name: "Levítico",             size: 27 },
  { id: "numeros",              name: "Números",              size: 36 },
  { id: "deuteronomio",         name: "Deuteronômio",         size: 34 },
  { id: "josue",                name: "Josué",                size: 24 },
  { id: "juizes",               name: "Juízes",               size: 21 },
  { id: "rute",                 name: "Rute",                 size: 4  },
  { id: "i-samuel",             name: "I Samuel",             size: 31 },
  { id: "ii-samuel",            name: "II Samuel",            size: 24 },
  { id: "i-reis",               name: "I Reis",               size: 22 },
  { id: "ii-reis",              name: "II Reis",              size: 25 },
  { id: "i-cronicas",           name: "I Crônicas",           size: 29 },
  { id: "ii-cronicas",          name: "II Crônicas",          size: 36 },
  { id: "esdras",               name: "Esdras",               size: 10 },
  { id: "neemias",              name: "Neemias",              size: 13 },
  { id: "tobias",               name: "Tobias",               size: 14 },
  { id: "judite",               name: "Judite",               size: 16 },
  { id: "ester",                name: "Ester",                size: 10 },
  { id: "i-macabeus",           name: "I Macabeus",           size: 16 },
  { id: "ii-macabeus",          name: "II Macabeus",          size: 15 },
  { id: "jo",                   name: "Jó",                   size: 42 },
  { id: "salmos",               name: "Salmos",               size: 150 },
  { id: "proverbios",           name: "Provérbios",           size: 31 },
  { id: "eclesiastes",          name: "Eclesiastes",          size: 12 },
  { id: "cantico-dos-canticos", name: "Cântico dos Cânticos", size: 8  },
  { id: "sabedoria",            name: "Sabedoria",            size: 19 },
  { id: "eclesiastico",         name: "Eclesiástico",         size: 51 },
  { id: "isaias",               name: "Isaías",               size: 66 },
  { id: "jeremias",             name: "Jeremias",             size: 52 },
  { id: "lamentacoes",          name: "Lamentações",          size: 5  },
  { id: "baruc",                name: "Baruc",                size: 6  },
  { id: "ezequiel",             name: "Ezequiel",             size: 48 },
  { id: "daniel",               name: "Daniel",               size: 14 },
  { id: "oseias",               name: "Oseias",               size: 14 },
  { id: "joel",                 name: "Joel",                 size: 3  },
  { id: "amos",                 name: "Amós",                 size: 9  },
  { id: "abdias",               name: "Abdias",               size: 1  },
  { id: "jonas",                name: "Jonas",                size: 4  },
  { id: "miqueias",             name: "Miqueias",             size: 7  },
  { id: "naum",                 name: "Naum",                 size: 3  },
  { id: "habacuc",              name: "Habacuc",              size: 3  },
  { id: "sofonias",             name: "Sofonias",             size: 3  },
  { id: "ageu",                 name: "Ageu",                 size: 2  },
  { id: "zacarias",             name: "Zacarias",             size: 14 },
  { id: "malaquias",            name: "Malaquias",            size: 3  },
  { id: "sao-mateus",           name: "São Mateus",           size: 28 },
  { id: "sao-marcos",           name: "São Marcos",           size: 16 },
  { id: "sao-lucas",            name: "São Lucas",            size: 24 },
  { id: "sao-joao",             name: "São João",             size: 21 },
  { id: "atos-dos-apostolos",   name: "Atos dos Apóstolos",   size: 28 },
  { id: "romanos",              name: "Romanos",              size: 16 },
  { id: "i-corintios",          name: "I Coríntios",          size: 16 },
  { id: "ii-corintios",         name: "II Coríntios",         size: 13 },
  { id: "galatas",              name: "Gálatas",              size: 6  },
  { id: "efesios",              name: "Efésios",              size: 6  },
  { id: "filipenses",           name: "Filipenses",           size: 4  },
  { id: "colossenses",          name: "Colossenses",          size: 4  },
  { id: "i-tessalonicenses",    name: "I Tessalonicenses",    size: 5  },
  { id: "ii-tessalonicenses",   name: "II Tessalonicenses",   size: 3  },
  { id: "i-timoteo",            name: "I Timóteo",            size: 6  },
  { id: "ii-timoteo",           name: "II Timóteo",           size: 4  },
  { id: "tito",                 name: "Tito",                 size: 3  },
  { id: "filemon",              name: "Filemon",              size: 1  },
  { id: "hebreus",              name: "Hebreus",              size: 13 },
  { id: "sao-tiago",            name: "São Tiago",            size: 5  },
  { id: "i-sao-pedro",          name: "I São Pedro",          size: 5  },
  { id: "ii-sao-pedro",         name: "II São Pedro",         size: 3  },
  { id: "i-sao-joao",           name: "I São João",           size: 5  },
  { id: "ii-sao-joao",          name: "II São João",          size: 1  },
  { id: "iii-sao-joao",         name: "III São João",         size: 1  },
  { id: "sao-judas",            name: "São Judas",            size: 1  },
  { id: "apocalipse",           name: "Apocalipse",           size: 22 }
];