export const catholicBookIds_la = [
  { id: "genesis",              name: "Genesis",               size: 50 },
  { id: "exodus",               name: "Exodus",                size: 40 },
  { id: "leviticus",            name: "Leviticus",             size: 27 },
  { id: "numeri",               name: "Numeri",                size: 36 },
  { id: "deuteronomium",        name: "Deuteronomium",         size: 34 },
  { id: "josue",                name: "Josue",                 size: 24 },
  { id: "judicum",              name: "Judicum",               size: 21 },
  { id: "ruth",                 name: "Ruth",                  size: 4  },
  { id: "1-regum",              name: "1 Regum",               size: 31 }, // 1 Samuel
  { id: "2-regum",              name: "2 Regum",               size: 24 }, // 2 Samuel
  { id: "3-regum",              name: "3 Regum",               size: 22 }, // 1 Kings
  { id: "4-regum",              name: "4 Regum",               size: 25 }, // 2 Kings
  { id: "1-paralipomenon",      name: "1 Paralipomenon",       size: 29 },
  { id: "2-paralipomenon",      name: "2 Paralipomenon",       size: 36 },
  { id: "esdras",               name: "Esdras",                size: 10 },
  { id: "nehemias",             name: "Nehemias",              size: 13 },
  { id: "tobias",               name: "Tobias",                size: 14 },
  { id: "judith",               name: "Judith",                size: 16 },
  { id: "hester",               name: "Hester",                size: 16 }, // Vulgate usually has additions, checked ch count? 10+6=16 typically in cath bibles
  { id: "1-machabaeorum",       name: "1 Machabaeorum",        size: 16 },
  { id: "2-machabaeorum",       name: "2 Machabaeorum",        size: 15 },
  { id: "job",                  name: "Job",                   size: 42 },
  { id: "psalmi",               name: "Psalmi",                size: 150 },
  { id: "proverbia",            name: "Proverbia",             size: 31 },
  { id: "ecclesiastes",         name: "Ecclesiastes",          size: 12 },
  { id: "canticum-canticorum",  name: "Canticum Canticorum",   size: 8  },
  { id: "sapientia",            name: "Sapientia",             size: 19 },
  { id: "ecclesiasticus",       name: "Ecclesiasticus",        size: 51 },
  { id: "isaias",               name: "Isaias",                size: 66 },
  { id: "jeremias",             name: "Jeremias",              size: 52 },
  { id: "lamentationes",        name: "Lamentationes",         size: 5  },
  { id: "baruch",               name: "Baruch",                size: 6  },
  { id: "ezechiel",             name: "Ezechiel",              size: 48 },
  { id: "daniel",               name: "Daniel",                size: 14 },
  { id: "osee",                 name: "Osee",                  size: 14 },
  { id: "joel",                 name: "Joel",                  size: 3  },
  { id: "amos",                 name: "Amos",                  size: 9  },
  { id: "abdias",               name: "Abdias",                size: 1  },
  { id: "jonas",                name: "Jonas",                 size: 4  },
  { id: "micheas",              name: "Micheas",               size: 7  },
  { id: "nahum",                name: "Nahum",                 size: 3  },
  { id: "habacuc",              name: "Habacuc",               size: 3  },
  { id: "sophonia",             name: "Sophonia",              size: 3  },
  { id: "aggaeus",              name: "Aggaeus",               size: 2  },
  { id: "zacharias",            name: "Zacharias",             size: 14 },
  { id: "malachias",            name: "Malachias",             size: 3  },
  { id: "matthaeus",            name: "Matthaeus",             size: 28 },
  { id: "marcus",               name: "Marcus",                size: 16 },
  { id: "lucas",                name: "Lucas",                 size: 24 },
  { id: "joannes",              name: "Joannes",               size: 21 },
  { id: "actus-apostolorum",    name: "Actus Apostolorum",     size: 28 },
  { id: "ad-romanos",           name: "Ad Romanos",            size: 16 },
  { id: "1-ad-corinthios",      name: "1 Ad Corinthios",       size: 16 },
  { id: "2-ad-corinthios",      name: "2 Ad Corinthios",       size: 13 },
  { id: "ad-galatas",           name: "Ad Galatas",            size: 6  },
  { id: "ad-ephesios",          name: "Ad Ephesios",           size: 6  },
  { id: "ad-philippenses",      name: "Ad Philippenses",       size: 4  },
  { id: "ad-colossenses",       name: "Ad Colossenses",        size: 4  },
  { id: "1-ad-thessalonicenses",name: "1 Ad Thessalonicenses", size: 5  },
  { id: "2-ad-thessalonicenses",name: "2 Ad Thessalonicenses", size: 3  },
  { id: "1-ad-timotheum",       name: "1 Ad Timotheum",        size: 6  },
  { id: "2-ad-timotheum",       name: "2 Ad Timotheum",        size: 4  },
  { id: "ad-titum",             name: "Ad Titum",              size: 3  },
  { id: "ad-philemonem",        name: "Ad Philemonem",         size: 1  },
  { id: "ad-hebraeos",          name: "Ad Hebraeos",           size: 13 },
  { id: "jacobi",               name: "Jacobi",                size: 5  },
  { id: "1-petri",              name: "1 Petri",               size: 5  },
  { id: "2-petri",              name: "2 Petri",               size: 3  },
  { id: "1-joannis",            name: "1 Joannis",             size: 5  },
  { id: "2-joannis",            name: "2 Joannis",             size: 1  },
  { id: "3-joannis",            name: "3 Joannis",             size: 1  },
  { id: "judae",                name: "Judae",                 size: 1  },
  { id: "apocalypsis",          name: "Apocalypsis",           size: 22 }
];
