export const catholicBookIds_fr = [
  { id: "genese",               name: "Genèse",               size: 50 },
  { id: "exode",                name: "Exode",                size: 40 },
  { id: "levitique",            name: "Lévitique",            size: 27 },
  { id: "nombres",              name: "Nombres",              size: 36 },
  { id: "deuteronome",          name: "Deutéronome",          size: 34 },
  { id: "josue",                name: "Josué",                size: 24 },
  { id: "juges",                name: "Juges",                size: 21 },
  { id: "ruth",                 name: "Ruth",                 size: 4  },
  { id: "1-samuel",             name: "1 Samuel",             size: 31 },
  { id: "2-samuel",             name: "2 Samuel",             size: 24 },
  { id: "1-rois",               name: "1 Rois",               size: 22 },
  { id: "2-rois",               name: "2 Rois",               size: 25 },
  { id: "1-chroniques",         name: "1 Chroniques",         size: 29 },
  { id: "2-chroniques",         name: "2 Chroniques",         size: 36 },
  { id: "esdras",               name: "Esdras",               size: 10 },
  { id: "nehemie",              name: "Néhémie",              size: 13 },
  { id: "tobie",                name: "Tobie",                size: 14 },
  { id: "judith",               name: "Judith",               size: 16 },
  { id: "esther",               name: "Esther",               size: 10 },
  { id: "1-maccabees",          name: "1 Maccabées",          size: 16 },
  { id: "2-maccabees",          name: "2 Maccabées",          size: 15 },
  { id: "job",                  name: "Job",                  size: 42 },
  { id: "psaumes",              name: "Psaumes",              size: 150 },
  { id: "proverbes",            name: "Proverbes",            size: 31 },
  { id: "ecclesiaste",          name: "Ecclésiaste",          size: 12 },
  { id: "cantique-des-cantiques", name: "Cantique des Cantiques", size: 8 },
  { id: "sagesse",              name: "Sagesse",              size: 19 },
  { id: "siracide",             name: "Siracide",             size: 51 },
  { id: "isaie",                name: "Isaïe",                size: 66 },
  { id: "jeremie",              name: "Jérémie",              size: 52 },
  { id: "lamentations",         name: "Lamentations",         size: 5  },
  { id: "baruch",               name: "Baruch",               size: 6  },
  { id: "ezechiel",             name: "Ézéchiel",             size: 48 },
  { id: "daniel",               name: "Daniel",               size: 14 },
  { id: "osee",                 name: "Osée",                 size: 14 },
  { id: "joel",                 name: "Joël",                 size: 3  },
  { id: "amos",                 name: "Amos",                 size: 9  },
  { id: "abdias",               name: "Abdias",               size: 1  },
  { id: "jonas",                name: "Jonas",                size: 4  },
  { id: "michee",               name: "Michée",               size: 7  },
  { id: "nahum",                name: "Nahum",                size: 3  },
  { id: "habacuc",              name: "Habacuc",              size: 3  },
  { id: "sophonie",             name: "Sophonie",             size: 3  },
  { id: "aggee",                name: "Aggée",                size: 2  },
  { id: "zacharie",             name: "Zacharie",             size: 14 },
  { id: "malachie",             name: "Malachie",             size: 3  },
  { id: "matthieu",             name: "Matthieu",             size: 28 },
  { id: "marc",                 name: "Marc",                 size: 16 },
  { id: "luc",                  name: "Luc",                  size: 24 },
  { id: "jean",                 name: "Jean",                 size: 21 },
  { id: "actes",                name: "Actes",                size: 28 },
  { id: "romains",              name: "Romains",              size: 16 },
  { id: "1-corinthiens",        name: "1 Corinthiens",        size: 16 },
  { id: "2-corinthiens",        name: "2 Corinthiens",        size: 13 },
  { id: "galates",              name: "Galates",              size: 6  },
  { id: "ephesiens",            name: "Éphésiens",            size: 6  },
  { id: "philippiens",          name: "Philippians",          size: 4  },
  { id: "colossiens",           name: "Colossiens",           size: 4  },
  { id: "1-thessaloniciens",    name: "1 Thessaloniciens",    size: 5  },
  { id: "2-thessaloniciens",    name: "2 Thessaloniciens",    size: 3  },
  { id: "1-timothee",           name: "1 Timothée",           size: 6  },
  { id: "2-timothee",           name: "2 Timothée",           size: 4  },
  { id: "tite",                 name: "Tite",                 size: 3  },
  { id: "philemon",             name: "Philémon",             size: 1  },
  { id: "hebreux",              name: "Hébreux",              size: 13 },
  { id: "jacques",              name: "Jacques",              size: 5  },
  { id: "1-pierre",             name: "1 Pierre",             size: 5  },
  { id: "2-pierre",             name: "2 Pierre",             size: 3  },
  { id: "1-jean",               name: "1 Jean",               size: 5  },
  { id: "2-jean",               name: "2 Jean",               size: 1  },
  { id: "3-jean",               name: "3 Jean",               size: 1  },
  { id: "jude",                 name: "Jude",                 size: 1  },
  { id: "apocalypse",           name: "Apocalypse",           size: 22 }
];
