export const catholicBookIds_pl = [
  { id: "ksiega-rodzaju", name: "Księga Rodzaju", size: 50 },
  { id: "ksiega-wyjscia", name: "Księga Wyjścia", size: 40 },
  { id: "ksiega-kaplanska", name: "Księga Kapłańska", size: 27 },
  { id: "ksiega-liczb", name: "Księga Liczb", size: 36 },
  { id: "ksiega-powtorzonego-prawa", name: "Księga Powtórzonego Prawa", size: 34 },
  { id: "ksiega-jozuego", name: "Księga Jozuego", size: 24 },
  { id: "ksiega-sedziow", name: "Księga Sedziów", size: 21 },
  { id: "ksiega-rut", name: "Księga Rut", size: 4 },
  { id: "1-ksiega-samuela", name: "1 Księga Samuela", size: 31 },
  { id: "2-ksiega-samuela", name: "2 Księga Samuela", size: 24 },
  { id: "1-ksiega-krolewska", name: "1 Księga Królewska", size: 22 },
  { id: "2-ksiega-krolewska", name: "2 Księga Królewska", size: 25 },
  { id: "1-ksiega-kronik", name: "1 Księga Kronik", size: 29 },
  { id: "2-ksiega-kronik", name: "2 Księga Kronik", size: 36 },
  { id: "ksiega-ezdrasza", name: "Księga Ezdrasza", size: 10 },
  { id: "ksiega-nehemiasza", name: "Księga Nehemiasza", size: 13 },
  { id: "ksiega-tobiasza", name: "Księga Tobiasza", size: 14 },
  { id: "ksiega-judyty", name: "Księga Judyty", size: 16 },
  { id: "ksiega-estery", name: "Księga Estery", size: 10 },
  { id: "ksiega-hioba", name: "Księga Hioba", size: 42 },
  { id: "ksiega-psalmow", name: "Księga Psalmów", size: 150 },
  { id: "1-machabejska", name: "1 Machabejska", size: 16 },
  { id: "2-machabejska", name: "2 Machabejska", size: 15 },
  { id: "ksiega-przyslow", name: "Księga Przysłów", size: 31 },
  { id: "ksiega-koheleta", name: "Księga Koheleta", size: 12 },
  { id: "piesn-nad-piesniami", name: "Pieśń nad pieśniami", size: 8 },
  { id: "ksiega-madrosci", name: "Księga Mądrości", size: 19 },
  { id: "madrosc-syracha", name: "Mądrość Syracha", size: 51 },
  { id: "ksiega-izajasza", name: "Księga Izajasza", size: 66 },
  { id: "ksiega-jeremiasza", name: "Księga Jeremiasza", size: 52 },
  { id: "lamentacje-jeremiasza", name: "Lamentacje Jeremiasza", size: 5 },
  { id: "ksiega-barucha", name: "Księga Barucha", size: 6 },
  { id: "ksiega-ezechiela", name: "Księga Ezechiela", size: 48 },
  { id: "ksiega-daniela", name: "Księga Daniela", size: 14 },
  { id: "ksiega-ozeasza", name: "Księga Ozeasza", size: 14 },
  { id: "ksiega-joela", name: "Księga Joela", size: 3 },
  { id: "ksiega-amosa", name: "Księga Amosa", size: 9 },
  { id: "ksiega-abdiasza", name: "Księga Abdiasza", size: 1 },
  { id: "ksiega-jonasza", name: "Księga Jonasza", size: 4 },
  { id: "ksiega-micheasza", name: "Księga Micheasza", size: 7 },
  { id: "ksiega-nahuma", name: "Księga Nahuma", size: 3 },
  { id: "ksiega-habakuka", name: "Księga Habakuka", size: 3 },
  { id: "ksiega-sofoniasza", name: "Księga Sofoniasza", size: 3 },
  { id: "ksiega-aggeusza", name: "Księga Aggeusza", size: 2 },
  { id: "ksiega-zachariasza", name: "Księga Zachariasza", size: 14 },
  { id: "ksiega-malachiasza", name: "Księga Malachiasza", size: 3 },
  { id: "ewangelia-mateusza", name: "Ewangelia Mateusza", size: 28 },
  { id: "ewangelia-marka", name: "Ewangelia Marka", size: 16 },
  { id: "ewangelia-lukasza", name: "Ewangelia Łukasza", size: 24 },
  { id: "ewangelia-jana", name: "Ewangelia Jana", size: 21 },
  { id: "dzieje-apostolskie", name: "Dzieje Apostolskie", size: 28 },
  { id: "list-do-rzymian", name: "List do Rzymian", size: 16 },
  { id: "1-list-do-koryntian", name: "1 List do Koryntian", size: 16 },
  { id: "2-list-do-koryntian", name: "2 List do Koryntian", size: 13 },
  { id: "list-do-galatow", name: "List do Galatów", size: 6 },
  { id: "list-do-efezjan", name: "List do Efezjan", size: 6 },
  { id: "list-do-filipian", name: "List do Filipian", size: 4 },
  { id: "list-do-kolosan", name: "List do Kolosan", size: 4 },
  { id: "1-list-do-tesaloniczan", name: "1 List do Tesaloniczan", size: 5 },
  { id: "2-list-do-tesaloniczan", name: "2 List do Tesaloniczan", size: 3 },
  { id: "1-list-do-tymoteusza", name: "1 List do Tymoteusza", size: 6 },
  { id: "2-list-do-tymoteusza", name: "2 List do Tymoteusza", size: 4 },
  { id: "list-do-tytusa", name: "List do Tytusa", size: 3 },
  { id: "list-do-filemona", name: "List do Filemona", size: 1 },
  { id: "list-do-hebrajczykow", name: "List do Hebrajczyków", size: 13 },
  { id: "list-jakuba", name: "List Jakuba", size: 5 },
  { id: "1-list-piotra", name: "1 List Piotra", size: 5 },
  { id: "2-list-piotra", name: "2 List Piotra", size: 3 },
  { id: "1-list-jana", name: "1 List Jana", size: 5 },
  { id: "2-list-jana", name: "2 List Jana", size: 1 },
  { id: "3-list-jana", name: "3 List Jana", size: 1 },
  { id: "list-judy", name: "List Judy", size: 1 },
  { id: "apokalipsa-sw-jana", name: "Apokalipsa Św. Jana", size: 22 },
];
