export const catholicBookIds_hu = [
  { id: "teremtes-konyve", name: "Teremtés könyve", size: 50 },
  { id: "kivonulas-konyve", name: "Kivonulás könyve", size: 40 },
  { id: "levitak-konyve", name: "Leviták könyve", size: 27 },
  { id: "szamok-konyve", name: "Számok könyve", size: 36 },
  { id: "masodik-torvenykonyv", name: "Második Törvénykönyv", size: 34 },
  { id: "jozsue-konyve", name: "Józsue könyve", size: 24 },
  { id: "birak-konyve", name: "Bírák könyve", size: 21 },
  { id: "rut-konyve", name: "Rut könyve", size: 4 },
  { id: "samuel-i-konyve", name: "Sámuel I. könyve", size: 31 },
  { id: "samuel-ii-konyve", name: "Sámuel II. könyve", size: 24 },
  { id: "kiralyok-i-konyve", name: "Királyok I. könyve", size: 22 },
  { id: "kiralyok-ii-konyve", name: "Királyok II. könyve", size: 25 },
  { id: "kronikak-i-konyve", name: "Krónikák I. könyve", size: 29 },
  { id: "kronikak-ii-konyve", name: "Krónikák II. könyve", size: 36 },
  { id: "ezdras-konyve", name: "Ezdrás könyve", size: 10 },
  { id: "nehemias-konyve", name: "Nehemiás könyve", size: 13 },
  { id: "tobias-konyve", name: "Tóbiás könyve", size: 14 },
  { id: "judit-konyve", name: "Judit könyve", size: 16 },
  { id: "eszter-konyve", name: "Eszter könyve", size: 10 },
  { id: "job-konyve", name: "Jób könyve", size: 42 },
  { id: "zsoltarok-konyve", name: "Zsoltárok könyve", size: 150 },
  { id: "makkabeusok-i-konyve", name: "Makkabeusok I. könyve", size: 16 },
  { id: "makkabeusok-ii-konyve", name: "Makkabeusok II. könyve", size: 15 },
  { id: "peldabeszedek-konyve", name: "Példabeszédek könyve", size: 31 },
  { id: "predikator-konyve", name: "Prédikátor könyve", size: 12 },
  { id: "enekek-eneke", name: "Énekek éneke", size: 8 },
  { id: "bolcsesseg-konyve", name: "Bölcsesség könyve", size: 19 },
  { id: "sirak-fia-konyve", name: "Sirák fia könyve", size: 51 },
  { id: "izajas-konyve", name: "Izajás könyve", size: 66 },
  { id: "jeremias-konyve", name: "Jeremiás könyve", size: 52 },
  { id: "siralmak-konyve", name: "Siralmak könyve", size: 5 },
  { id: "baruk-konyve", name: "Báruk könyve", size: 6 },
  { id: "ezekiel-konyve", name: "Ezekiel könyve", size: 48 },
  { id: "daniel-konyve", name: "Dániel könyve", size: 14 },
  { id: "ozeas-konyve", name: "Ozeás könyve", size: 14 },
  { id: "joel-konyve", name: "Joel könyve", size: 3 },
  { id: "amosz-konyve", name: "Ámosz könyve", size: 9 },
  { id: "abdias-konyve", name: "Abdiás könyve", size: 1 },
  { id: "jonas-konyve", name: "Jónás könyve", size: 4 },
  { id: "mikeas-konyve", name: "Mikeás könyve", size: 7 },
  { id: "nahum-konyve", name: "Náhum könyve", size: 3 },
  { id: "habakuk-konyve", name: "Habakuk könyve", size: 3 },
  { id: "szofonias-konyve", name: "Szofoniás könyve", size: 3 },
  { id: "aggeus-konyve", name: "Aggeus könyve", size: 2 },
  { id: "zakarias-konyve", name: "Zakariás könyve", size: 14 },
  { id: "malakias-konyve", name: "Malakiás könyve", size: 3 },
  { id: "mate-evangeliuma", name: "Máté evangéliuma", size: 28 },
  { id: "mark-evangeliuma", name: "Márk evangéliuma", size: 16 },
  { id: "lukacs-evangeliuma", name: "Lukács evangéliuma", size: 24 },
  { id: "janos-evangeliuma", name: "János evangéliuma", size: 21 },
  { id: "apostolok-cselekedetei", name: "Apostolok Cselekedetei", size: 28 },
  { id: "romaiaknak-irt-level", name: "Rómaiaknak írt levél", size: 16 },
  { id: "korintusiaknak-irt-i-level", name: "Korintusiaknak írt I. levél", size: 16 },
  { id: "korintusiaknak-irt-ii-level", name: "Korintusiaknak írt II. levél", size: 13 },
  { id: "galataknak-irt-level", name: "Galatáknak írt levél", size: 6 },
  { id: "efezusiaknak-irt-level", name: "Efezusiaknak írt levél", size: 6 },
  { id: "filippieknek-irt-level", name: "Filippieknek írt levél", size: 4 },
  { id: "kolosszeieknek-irt-level", name: "Kolosszeieknek írt levél", size: 4 },
  { id: "tesszalonikaiaknak-irt-i-level", name: "Tesszalonikaiaknak írt I. levél", size: 5 },
  { id: "tesszalonikaiaknak-irt-ii-level", name: "Tesszalonikaiaknak írt II. levél", size: 3 },
  { id: "timoteusnak-irt-i-level", name: "Timóteusnak írt I. levél", size: 6 },
  { id: "timoteusnak-irt-ii-level", name: "Timóteusnak írt II. levél", size: 4 },
  { id: "titusznak-irt-level", name: "Titusznak írt levél", size: 3 },
  { id: "filemonnak-irt-level", name: "Filemonnak írt levél", size: 1 },
  { id: "zsidoknak-irt-level", name: "Zsidóknak írt levél", size: 13 },
  { id: "szent-jakab-levele", name: "Szent Jakab levele", size: 5 },
  { id: "szent-peter-i-levele", name: "Szent Péter I. levele", size: 5 },
  { id: "szent-peter-ii-levele", name: "Szent Péter II. levele", size: 3 },
  { id: "szent-janos-i-levele", name: "Szent János I. levele", size: 5 },
  { id: "szent-janos-ii-levele", name: "Szent János II. levele", size: 1 },
  { id: "szent-janos-iii-levele", name: "Szent János III. levele", size: 1 },
  { id: "szent-judas-levele", name: "Szent Júdás levele", size: 1 },
  { id: "jelenesek-konyve", name: "Jelenések könyve", size: 22 },
];
